config/routes.rb
Tyne::Application.routes.draw do
  mount Jasminerice::Engine => "/jasmine" if defined?(Jasminerice)
  devise_for :users
  get '/login', :action => "new", :as => :login, :controller => "sessions"
  get "/auth/:provider/callback", :action => "create", :as => :auth, :controller => "sessions"
  get "/auth/failure", :action => "failure", :as => :failure, :controller => "sessions"
  delete "/logout", :action => "destroy", :as => :logout, :controller => "sessions"
  get "/logout", :action => "destroy", :as => :logout, :controller => "sessions"

  resources :projects do
    resources :labels, :only => [:create, :destroy]
  end

  resources :dashboards

  get '/:user', :controller => 'users', :action => :overview, :as => :overview
  get '/:user/account_settings', :controller => 'users', :action => :edit, :as => :edit_account_settings
  put '/:user/account_settings', :controller => 'users', :action => :update, :as => :account_settings
  get '/:user/:key', :controller => 'issues', :action => 'index', :as => :backlog
  scope '/:user/:key' do
    get :admin, :controller => 'projects', :action => :admin, :as => :admin_project
    resources :issues do
      collection do
        get :dialog
        post :reorder
      end

      member do
        get :workflow
        post :upvote
        post :downvote
        post :assign_to_me
        put :assign_to_user
      end

      resources :comments
    end

    resources :teams do
      member do
        get :suggest_user
      end
      resources :team_members
    end

    resources :sprints do
      member do
        post :reorder
        put :start
        put :finish
      end
      collection do
        get :current
      end
    end

    resources :reports, :only => [:index] do
      collection do
        get :issue_type_ratio
        get :burn_down
      end
    end
  end
  root :to => "dashboards#index"
end

app/models/label.rb
# A label for an issue
class Label < ActiveRecord::Base
  belongs_to :project
  has_many :issue_labels, :dependent => :destroy
  has_many :issues, :through => :issue_labels

  attr_accessible :name, :colour

  validates :name, :presence => true
  validates :name, :uniqueness => { :scope => :project_id }
end

app/controllers/labels_controller.rb
# Handles requests for labels
class LabelsController < ApplicationController
  self.responder = ::ApplicationResponder
  respond_to :html, :json

  before_filter :load_label_project
  before_filter :require_login
  before_filter :ensure_can_collaborate

  # Creates a new label for a project
  def create
    @label = @project.labels.build(params[:label])
    @label.save

    respond_with(@label) do |format|
      format.pjax { render @label, :locals => { :issue => nil } }
    end
  end

  # Deletes a label for a project
  def destroy
    @label = @project.labels.find_by_id(params[:id])

    @label.destroy
    respond_with(@label) do |format|
      format.js { render {} }
    end
  end

  private
  def load_label_project
    @project = Project.find_by_id(params[:project_id])
    @user = @project.user
  end
end

app/helpers/labels_helper.rb
# View helpers for labels
module LabelsHelper
  # Determines if a label is assigned to an issue
  def labelled?(label, issue)
    return false unless issue

    label.issues.include?(issue)
  end

  # Returns the associated label identifier
  def labelled_id(label, issue)
    return unless issue

    labelled = label.issue_labels.find_by_issue_id(issue.id)
    labelled.id if labelled
  end

  # Renders a tag for a label.
  def tag_for_label(label)
    style = "background-color: #{label.colour}; color:#{black_or_white(label.colour)}"
    content_tag :span, label.name, :class => "tag", :title => label.name, :style => style
  end

  private
  def black_or_white(colour)
    if bright?(colour)
      "#000000"
    else
      "#FFFFFF"
    end
  end

  def bright?(colour)
    red = colour[1,2].to_i(16)
    green = colour[3,2].to_i(16)
    blue = colour[5,2].to_i(16)

    luminance_standard(red, green, blue) > (255/2)
  end

  def luminance_standard(red, green, blue)
    return (0.2126*red) + (0.7152*green) + (0.0722*blue);
  end
end

app/views/labels/_label.pjax.erb
<li class="<%= labelled?(label, issue) ? "selected" : "" %>">
<label data-id="<%= label.id %>" data-present="<%= labelled_id(label, issue) %>" data-colour="<%= label.colour %>" style="background-color: <%= labelled?(label, issue) ? label.colour : "transparent" %>; color: <%= labelled?(label, issue) ? black_or_white(label.colour) : label.colour %>"><%= label.name %></label>
  <%= link_to(content_tag(:i, "", :class => "icon-trash"), project_label_path(:project_id => @project.id, :id => label.id), :method => :delete, :remote => true, :confirm => "Are you sure you wish to delete this label?", :data => { :"confirm-title" => "Delete Label", :"confirm-proceed" => "Delete", :"confirm-proceed-class" => "btn-danger" }) %>
</li>

app/views/labels/_label_form.html.erb
<%= simple_form_for(@label, :validate => true, :url => project_labels_path(:project_id => @project.id, :format => :pjax), :html => { :class => "form-inline" }) do |f| %>
  <%= f.input :colour, :label => false, :input_html => { :data => { :type => "colour" }, :value => "#555555" } %>
  <%= f.input :name, :placeholder => "Type to enter label", :label => false %>
  <%= f.button :submit, :class => "btn" %>
<% end %>

app/views/labels/_labels.html.erb
<div class="labels" data-cell="Labels">
  <h1>Manage Labels</h1>
    <ul class="labels-list">
      <%= render :partial => "labels/label", :collection => @issue.project.labels, :formats => [:pjax], :locals => { :issue => @issue } %>
    </ul>
  <%= render :partial => "labels/label_form", :locals => { :label => @label } %>
</div>

app/views/labels/destroy.js.erb
$('.labels ul li label[data-id="<%= @label.id %>"]').closest("li").remove();

Notification.show('success', I18n.t("flash.actions.destroy.notice", {resource_name: "Label"}));