config/routes.rb
Tyne::Application.routes.draw do
  mount Jasminerice::Engine => "/jasmine" if defined?(Jasminerice)
  devise_for :users
  get '/login', :action => "new", :as => :login, :controller => "sessions"
  get "/auth/:provider/callback", :action => "create", :as => :auth, :controller => "sessions"
  get "/auth/failure", :action => "failure", :as => :failure, :controller => "sessions"
  delete "/logout", :action => "destroy", :as => :logout, :controller => "sessions"
  get "/logout", :action => "destroy", :as => :logout, :controller => "sessions"

  resources :projects do
    resources :labels, :only => [:create, :destroy]
  end

  resources :dashboards

  get '/:user', :controller => 'users', :action => :overview, :as => :overview
  get '/:user/account_settings', :controller => 'users', :action => :edit, :as => :edit_account_settings
  put '/:user/account_settings', :controller => 'users', :action => :update, :as => :account_settings
  get '/:user/:key', :controller => 'issues', :action => 'index', :as => :backlog
  scope '/:user/:key' do
    get :admin, :controller => 'projects', :action => :admin, :as => :admin_project
    resources :issues do
      collection do
        get :dialog
        post :reorder
      end

      member do
        get :workflow
        post :upvote
        post :downvote
        post :assign_to_me
        put :assign_to_user
      end

      resources :comments
    end

    resources :teams do
      member do
        get :suggest_user
      end
      resources :team_members
    end

    resources :sprints do
      member do
        post :reorder
        put :start
        put :finish
      end
      collection do
        get :current
      end
    end

    resources :reports, :only => [:index] do
      collection do
        get :issue_type_ratio
        get :burn_down
      end
    end
  end
  root :to => "dashboards#index"
end

app/models/sprint.rb
# A Sprint is an iteration to deliver a subset of your product backlog
# in a certain time frame.
class Sprint < ActiveRecord::Base
  attr_accessible :end_date, :name, :project_id, :start_date

  belongs_to :project
  has_many :issues, :class_name => 'SprintItem', :order => 'sprint_position', :dependent => :nullify
  has_many :activities, :class_name => 'SprintActivity', :extend => SprintActivity::ScopeExtensions, :autosave => true

  validates :name, :start_date, :end_date, :project_id, :presence => true
  validates :active, :uniqueness => { :scope => :project_id }, :if => :active

  after_initialize :set_dates

  scope :not_running, where(:active => false, :finished => nil)

  scope :in_progress, where(:finished => nil)

  # Starts the sprint. Only valid if there is no running sprint.
  def start(start_date, end_date)
    self.start_date = start_date
    self.end_date = end_date
    self.active = true
    issues.each do |issue|
      log_activity(issue, 'start', issue.estimate)
    end
    save
  end

  # Creates a log event to indicate a scope change (e.g. sprint started, issue closed).
  def log_activity(issue, type, change)
    activities.build(:issue_id => issue.id,
                     :type_of_change => type,
                     :scope_change => change)
  end

  # Finishes the sprint.
  def finish
    self.issues.not_completed.update_all(:sprint_id => nil, :sprint_position => nil)
    self.finished = DateTime.now
    self.active = false
    save
  end

  private
  def set_dates
    self.start_date ||= Date.today.to_date
    self.end_date ||= 7.days.from_now.to_date
  end
end

app/controllers/sprints_controller.rb
# Handles request for sprints of a project
class SprintsController < AdminController
  self.responder = ::ApplicationResponder
  respond_to :html, :json, :pjax

  before_filter :load_user
  before_filter :load_project
  before_filter :require_login, :except => [:current]
  before_filter :ensure_can_collaborate, :except => [:current]

  helper :issues

  # Displays the planning page.
  def index
    add_breadcrumb :planning

    @sprints = @project.sprints.in_progress
    @issues = @project.backlog_items.not_completed.where(:sprint_id => nil)
  end

  # Creates a new sprint.
  def create
    @sprint = @project.sprints.create(:name => "Unnamed sprint")

    render @sprint
  end

  # Upates a sprint
  def update
    @sprint = @project.sprints.find(params[:id])
    @sprint.update_attributes(params[:sprint])
    respond_with(@sprint)
  end

  # Destroys a sprint
  def destroy
    @sprint = @project.sprints.find(params[:id])
    if @sprint.destroy
      render :json => :ok
    else
      render :json => { :errors => @sprint.errors }, :status => :entity_unprocessable
    end
  end

  # Changes the ranking inside a particular sprint. If the item is not already
  # in the sprint it will be added.
  # The item will get removed from the backlog if it used to be there.
  def reorder
    @issue = @project.sprint_items.find(params[:issue_id])
    @issue.becomes(BacklogItem).remove_from_list

    @issue.remove_from_list

    @issue.sprint_id = @project.sprints.find(params[:id]).id
    @issue.save

    if @issue.insert_at(params[:position].to_i)
      render :json => :ok
    else
      render :json => { :errors => @issue.errors }, :status => :entity_unprocessable
    end
  end

  # Starts a new sprint.
  def start
    @sprint = @project.sprints.find(params[:id])
    @sprint.start(params[:sprint][:start_date], params[:sprint][:end_date])

    respond_with(@sprint, :location => current_sprints_path(:user => @project.user.username, :key => @project.key))
  end

  # Finishes a sprint.
  def finish
    @sprint = @project.sprints.find(params[:id])
    @sprint.finish

    respond_with(@sprint, :location => sprints_path(:user => @project.user.username, :key => @project.key))
  end

  # Displays the agile board
  def current
    add_breadcrumb :current
    @sprint = @project.sprints.find_by_active(true)
  end
end

app/helpers/sprints_helper.rb
# Provides view helpers for the sprints in the core engine.
module SprintsHelper
  # Renders a start sprint for a particular sprint.
  # The button will be disabled if either a sprint is already running
  # or if the sprint is empty (no issues).
  def start_sprint_button(sprint)
    options = { :class => "btn btn-small start-sprint", :data => { :toggle => 'modal', :target => "#sprint_#{sprint.id}_dialog" } }

    title = ""

    if sprint.issues.empty?
      options[:disabled] = :disabled
      title = t("sprints.zero_issues")
    end

    if @project.any_running?
      options[:disabled] = :disabled
      options[:data][:running] = true
      title = t("sprints.already_running")
    end

    options[:title] = title unless title.empty?

    button_tag sprint_action(sprint), options
  end

  def sprint_action sprint
    sprint.active? ? "Current Sprint" : "Start"
  end
  # Renders a button to finish the sprint. The action requires a confirmation.
  def finish_button
    finish_url = finish_sprint_path(:user => @sprint.project.user.username, :key => @sprint.project.key, :id => @sprint.id)
    data = {
      :"confirm-title" => "Finish sprint #{@sprint.name}",
      :"confirm-proceed" => "Finish",
      :"confirm-proceed-class" => "btn-success"
    }
    options = {
      :class => "btn btn-small",
      :confirm => "Are you sure you wish to finish your sprint?",
      :method => :put,
      :data => data
    }
    link_to("Finish", finish_url, options)
  end

  # Renders a link to the burn down chart
  def burn_down_link
    link_to("View Burn Down", burn_down_reports_path(:user => @sprint.project.user.username, :key => @sprint.project.key))
  end
end

app/views/sprints/_drag_information.html.erb
<div class="board-drag-information">
  You can drag issues into the area above to perform a workflow transition.
</div>

app/views/sprints/_issue.html.erb
<% cache ["v3", "backlog", issue] do %>
<li class="backlog-issue issue <%= issue.state %> state-<%= issue.issue_type.name.downcase %>" data-id="<%= issue.id %>" data-cell="BacklogItem">
  <div class="td-first dragger"></div>
  <div class="td-second">
    <p class="issue-headline issue-line-1">
      <span class="issue-type-short">
        <%= issue_type(issue, true) %>
      </span>

      <%= issue_id(issue) %>
      <span class="issue-summary"><%= content_tag :span, issue.summary, :class => "issue-#{issue.state}" %></span>
      <%= best_in_place issue.becomes(Issue), :estimate, :path => path_to_issue(issue), :inner_class => :estimate, :classes => 'estimates' %>
    </p>
  </div>
</li>
<% end %>

app/views/sprints/_sprint.html.erb
<div class="well no-padding planning-sprint" data-cell="SprintDeletion">
  <div class="sprint-header">
    <span class="planning-sprint-name"><%= best_in_place sprint, :name, :type => :input, :path => main_app.sprint_path(:id => sprint.id, :user => sprint.project.user.username, :key => sprint.project.key) %></span>
    <span class="issue-count"><%= pluralize(sprint.issues.count, "Issue") %></span>
    <%= start_sprint_button(sprint) %>
    <%= link_to "&times;".html_safe, main_app.sprint_path(:user => @project.user.username, :key => @project.key, :id => sprint.id), :class => "delete-sprint close", :confirm => "Are you sure you want to delete this sprint?", :method => :delete, :remote => true, :data => { :"confirm-title" => "Delete #{sprint.name}", :"confirm-proceed" => "Delete", :"confirm-proceed-class" => "btn-danger" } %>
  </div>

  <ul class="planning-sprint-items backlog-sortable backlog-connected" data-reorder-url="<%= main_app.reorder_sprint_path(:user => @project.user.username, :key => @project.key, :id => sprint.id) %>">
      <%= render :partial => "issue", :collection => sprint.issues %>
  </ul>
  <div class="planning-sprint-drag-information">
    Drag items from the backlog into this area to add it to the sprint.
  </div>
</div>
<%= render :partial => 'sprint_dialog', :locals => { :sprint => sprint } %>

app/views/sprints/_sprint_dialog.html.erb
<div id="<%= "sprint_#{sprint.id}_dialog" %>" class="modal hide fade" tabindex="-1" role="dialog">
  <%= simple_form_for(sprint, :url => main_app.start_sprint_path(:user => sprint.project.user.username, :key => sprint.project.key, :id => sprint.id), :validate => true) do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>Start <%= sprint.name %></h3>
  </div>
  <div class="modal-body">
    <%= f.input :start_date, :as => :datepicker %>
    <%= f.input :end_date, :as => :datepicker %>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <%= f.button :submit, :value => 'Start sprint', :class => 'btn btn-success' %>
  </div>
  <% end %>
</div>

app/views/sprints/_sprint_placeholder.html.erb
<div class="planning-new" data-cell="Sprint" data-url="<%= main_app.sprints_path(:user => @project.user.username, :key => @project.key, :format => :pjax) %>">Click here to create a new sprint</div>

app/views/sprints/_work_item.html.erb
<li class="work-item state-<%= work_item.issue_type.name.downcase %>" data-state="<%= work_item.state %>" data-workflow-path="<%= workflow_issue_path(:user => @sprint.project.user.username, :key => @sprint.project.name, :id => work_item.number, :format => :json) %>">
  <div class="work-item-content">
    <table>
      <tr>
        <td class="dragger"></td>
        <td class="work-item-main">
          <div class="work-item-key"><%= issue_id(work_item) %></div>
          <div class="work-item-summary"><%= work_item.summary %></div>
        </td>
        <td class="td-last">
          <div class="work-item-gravatar"><%= avatar(work_item.assigned_to, :width => 32) %></div>
        </td>
      </tr>
    </table>
  </div>
</li>

app/views/sprints/current.html.erb
<% if @sprint %>
  <div class="options">
    <%= finish_button if is_owner? %>
    <div class="pull-right">
      <%= content_tag :span, "#{@sprint.start_date.to_formatted_s(:short)} - #{@sprint.end_date.to_formatted_s(:short)}" %>
      <% if is_collaborator? %>
      | <%= burn_down_link %>
      <% end %>
    </div>
  </div>

  <div class="board" data-collab="<%= is_collaborator? %>">
    <div class="row-fluid">
    <div class="span4">
      <div class="well">
        <h3>To Do</h3>
        <ul class="work-items sortable connected" data-state="todo">
          <%= render :partial => 'sprints/work_item', :collection => @sprint.issues.to_do %>
        </ul>
        <%= render :partial => "drag_information" if is_collaborator? %>
      </div>
    </div>

    <div class="span4">
      <div class="well">
        <h3>In Progress</h3>
        <ul class="work-items sortable connected" data-state="progress">
          <%= render :partial => 'sprints/work_item', :collection => @sprint.issues.in_progress %>
        </ul>
        <%= render :partial => "drag_information" if is_collaborator? %>
      </div>
    </div>

    <div class="span4">
      <div class="well">
        <h3>Done</h3>
        <ul class="work-items sortable connected" data-state="done">
          <%= render :partial => 'sprints/work_item', :collection => @sprint.issues.closed %>
        </ul>
        <%= render :partial => "drag_information" if is_collaborator? %>
      </div>
    </div>
    </div>
  </div>
<% else %>
  <div class="row-fluid">
    <div class="span12">
      <div class="well centered">
        <p>There is currently no active sprint.</p>
      </div>
    </div>
  </div>
<% end %>

app/views/sprints/index.html.erb
<div class="span6">
  <div class="options">
    <%= link_to "Create", new_issue_path(:user => @project.user.username, :key => @project.key), :class => "btn btn-small" if current_user %>
  </div>

  <div class="well no-padding backlog">
    <div class="backlog-headline">
      <span class="backlog-headline-content">Backlog</span>
      <span class="backlog-headline-issue-count issue-count"><%= pluralize(@issues.count, "Issue") %></span>
    </div>

    <ul class="backlog-items backlog-sortable backlog-connected" data-reorder-url="<%= reorder_issues_path(:user => @project.user.username, :key => @project.key) %>">
      <%= render :partial => "issue", :collection => @issues %>
    </ul>
  </div>
</div>

<div class="span6">
  <div class="planning">
    <%= render @sprints %>
    <%= render :partial => "sprint_placeholder" %>
  </div>
</div>