config/routes.rb
Tyne::Application.routes.draw do
  mount Jasminerice::Engine => "/jasmine" if defined?(Jasminerice)
  devise_for :users
  get '/login', :action => "new", :as => :login, :controller => "sessions"
  get "/auth/:provider/callback", :action => "create", :as => :auth, :controller => "sessions"
  get "/auth/failure", :action => "failure", :as => :failure, :controller => "sessions"
  delete "/logout", :action => "destroy", :as => :logout, :controller => "sessions"
  get "/logout", :action => "destroy", :as => :logout, :controller => "sessions"

  resources :projects do
    resources :labels, :only => [:create, :destroy]
  end

  resources :dashboards

  get '/:user', :controller => 'users', :action => :overview, :as => :overview
  get '/:user/account_settings', :controller => 'users', :action => :edit, :as => :edit_account_settings
  put '/:user/account_settings', :controller => 'users', :action => :update, :as => :account_settings
  get '/:user/:key', :controller => 'issues', :action => 'index', :as => :backlog
  scope '/:user/:key' do
    get :admin, :controller => 'projects', :action => :admin, :as => :admin_project
    resources :issues do
      collection do
        get :dialog
        post :reorder
      end

      member do
        get :workflow
        post :upvote
        post :downvote
        post :assign_to_me
        put :assign_to_user
      end

      resources :comments
    end

    resources :teams do
      member do
        get :suggest_user
      end
      resources :team_members
    end

    resources :sprints do
      member do
        post :reorder
        put :start
        put :finish
      end
      collection do
        get :current
      end
    end

    resources :reports, :only => [:index] do
      collection do
        get :issue_type_ratio
        get :burn_down
      end
    end
  end
  root :to => "dashboards#index"
end

app/controllers/reports_controller.rb
# Handles requests for reports
class ReportsController < ApplicationController
  self.responder = ::ApplicationResponder
  respond_to :html, :json, :pjax

  before_filter :load_user
  before_filter :load_project
  before_filter :require_login
  before_filter :ensure_can_collaborate
  before_filter :add_report_breadcrumb

  # Displays the list of all available reports (e.g. Issue Type Ratio)
  def index; end

  # Displays the issue type ratio report
  def issue_type_ratio
    add_breadcrumb :issue_type_ratio

    report = Reports::IssueTypeRatio.new(@project)
    @chart = report.to_chart
  end

  # Displays a burn down chart
  def burn_down
    add_breadcrumb :burn_down

    report = Reports::BurnDown.new(@project.current_sprint)
    @chart = report.to_chart
  end

  private

  def add_report_breadcrumb
    add_breadcrumb :index, reports_path(:user => @user.username, :key => @project.key)
  end
end

app/helpers/reports_helper.rb
# Provides view helper methods for report area
module ReportsHelper
end

app/views/reports/burn_down.html.erb
<% content_for :head_assets do %>
  <%= javascript_include_tag "https://www.google.com/jsapi" %>
<% end %>

<div class="span12">
  <div class="well">
    <h1 class="report-headline">Burn Down</h1>
    <p class="report-description">This report displays the burn down chart and activity for the current sprint.</p>

    <% if @project.current_sprint %>
      <%= content_tag :p, "#{@project.current_sprint.start_date.to_formatted_s(:short)} - #{@project.current_sprint.end_date.to_formatted_s(:short)}" %>
      <div id='chart'></div>
      <%= render_chart(@chart, 'chart') if @chart %>
    <% else %>
      <%= content_tag :p, "There is currently no active sprint." %>
    <% end %>
  </div>
</div>

app/views/reports/index.html.erb
<div class="span12">
  <div class="well reports">
    <ul>
      <li>
        <h2>Burn Down Chart</h2>
        <p>Displays a graph that represents your work left to do versus time for the current sprint.</p>
        <%= link_to "View Burn Down Chart", burn_down_reports_path(:user => @user.username, :key => @project.key) %>
      </li>
      <li>
        <h2>Issue Type Ratio</h2>
        <p>Displays a pie chart the represents the ratio of your issue types.</p>
        <%= link_to "View Issue Type Ratio Report", issue_type_ratio_reports_path(:user => @user.username, :key => @project.key) %>
      </li>
    </ul>
    <br />
  </div>
</div>

app/views/reports/issue_type_ratio.html.erb
<% content_for :head_assets do %>
  <%= javascript_include_tag "https://www.google.com/jsapi" %>
<% end %>

<div class="span12">
  <div class="well">
    <h1 class="report-headline">Issue Type Ratio</h1>
    <p class="report-description">This report displays the issue type ratio.</p>

    <div id='chart'></div>
    <%= render_chart(@chart, 'chart') %>
  </div>
</div>