config/routes.rb
Tyne::Application.routes.draw do
  mount Jasminerice::Engine => "/jasmine" if defined?(Jasminerice)
  devise_for :users
  get '/login', :action => "new", :as => :login, :controller => "sessions"
  get "/auth/:provider/callback", :action => "create", :as => :auth, :controller => "sessions"
  get "/auth/failure", :action => "failure", :as => :failure, :controller => "sessions"
  delete "/logout", :action => "destroy", :as => :logout, :controller => "sessions"
  get "/logout", :action => "destroy", :as => :logout, :controller => "sessions"

  resources :projects do
    resources :labels, :only => [:create, :destroy]
  end

  resources :dashboards

  get '/:user', :controller => 'users', :action => :overview, :as => :overview
  get '/:user/account_settings', :controller => 'users', :action => :edit, :as => :edit_account_settings
  put '/:user/account_settings', :controller => 'users', :action => :update, :as => :account_settings
  get '/:user/:key', :controller => 'issues', :action => 'index', :as => :backlog
  scope '/:user/:key' do
    get :admin, :controller => 'projects', :action => :admin, :as => :admin_project
    resources :issues do
      collection do
        get :dialog
        post :reorder
      end

      member do
        get :workflow
        post :upvote
        post :downvote
        post :assign_to_me
        put :assign_to_user
      end

      resources :comments
    end

    resources :teams do
      member do
        get :suggest_user
      end
      resources :team_members
    end

    resources :sprints do
      member do
        post :reorder
        put :start
        put :finish
      end
      collection do
        get :current
      end
    end

    resources :reports, :only => [:index] do
      collection do
        get :issue_type_ratio
        get :burn_down
      end
    end
  end
  root :to => "dashboards#index"
end

app/views/layouts/_administration.html.erb
<% content_for :sidebar do %>
  <ul class="nav nav-list">
    <li><%= link_to "Projects (#{current_user.projects.count})", tyne_core.projects_path %></li>
  </ul>
<% end if admin_area? %>

app/views/layouts/_logged_in.html.erb
<%= render :partial => 'layouts/menu' %>

<ul class="nav pull-right">
  <li>
    <%= link_to "New Issue", new_issue_path(:user => @project.user.username, :key => @project.key), :class => "new-issue-link-menu" if @project && @project.persisted? %>
  </li>
  <li>
  <%= link_to content_tag(:span, "", :class => 'icon-plus'), new_project_path, :class => "new-project-link tooltipped-bottom", :title => "Create a new project", :data => { :toggle => 'tooltip' } %>
  </li>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="user_dropdown">
      <%#= avatar(current_user) %>
      <%= current_user.username %>
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to "Account settings", edit_account_settings_path(:user => current_user.username) %></li>
      <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
    </ul>
  </li>
</ul>

app/views/layouts/_logged_out.html.erb
<%= render :partial => 'layouts/menu' %>

<div class="pull-right">
  <%= link_to "Sign in", login_path(:redirect_url => request.path), :class=> "btn btn-small sign-in"  %>
</div>

app/views/layouts/_menu.html.erb
<% if @project && @project.key %>
  <%= cache ["v2", "menu", current_user, @project, is_collaborator?] do %>
    <ul class="nav">
        <%= content_tag(:li, link_to("Backlog", main_app.issues_path(:user => @project.user.username, :key => @project.key))) %>
        <%= content_tag(:li, link_to("Planning", main_app.sprints_path(:user => @project.user.username, :key => @project.key))) if is_collaborator? %>
        <%= content_tag(:li, link_to("Current Sprint", main_app.current_sprints_path(:user => @project.user.username, :key => @project.key))) %>
        <%= content_tag(:li, link_to("Reports", main_app.reports_path(:user => @project.user.username, :key => @project.key))) if is_collaborator? %>
        <%= content_tag(:li, link_to("Admin", main_app.admin_project_path(:user => @project.user.username, :key => @project.key), :class => 'admin-link')) if @project.user == current_user %>
    </ul>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= page_title %></title>

    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= yield(:head_assets) if content_for?(:head_assets) %>
  </head>
  <body class="logged_<%= current_user ? "in" : "out" %> page-<%= controller.controller_name %>-<%= params[:action] %>">
    <div class="wrapper">
      <div class="navbar navbar-fixed-top navbar-inverse">
        <div class="navbar-inner">
          <div class="container-fluid">
            <a class="brand" href="<%= main_app.root_path %>"><%= brand %></a>
            <div class="container-fluid nav-collapse">
              <% if current_user %>
                <%= render :partial => "layouts/logged_in" %>
              <% else %>
                <%= render :partial => "layouts/logged_out" %>
              <% end %>
            </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>

      <div class="breadcrumb-wrapper">
        <%= render_breadcrumbs %>
      </div>

      <div class="container-fluid">

        <div class="row-fluid">
          <%= yield %>
        </div><!--/row-->

      </div> <!-- /container -->
      <div class="push"></div>
    </div> <!-- /wrap-->

    <div class="footer">
      <footer>
        <div class="container">
          <p>&copy; Pravin Mhatre 2012 - 2013 | v<%= VERSION %> | <a href="https://github.com/prawin/tracktor">Fork me on Github</a></p>
        </div>
      </footer>
    </div>

    <%= render_cell :notification, :show %>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

    <%= flash_notification %>


    <!-- UserVoice JavaScript SDK (only needed once on a page) -->
    <script>(function(){var uv=document.createElement('script');uv.type='text/javascript';uv.async=true;uv.src='//widget.uservoice.com/4XpjMTq2Td5fNXBJGZYLw.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(uv,s)})()</script>

    <!-- A tab to launch the Classic Widget -->
    <script>
      UserVoice = window.UserVoice || [];
      UserVoice.push(['showTab', 'classic_widget', {
        mode: 'full',
        primary_color: '#cc6d00',
        link_color: '#007dbf',
        default_mode: 'support',
        forum_id: 233717,
        tab_label: 'Feedback & Support',
        tab_color: '#cc6d00',
        tab_position: 'bottom-right',
        tab_inverted: false
      }]);
    </script>
  </body>
</html>